-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Drinkki CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Käyttäjä CASCADE;
DROP TABLE IF EXISTS Nimi CASCADE;
DROP TABLE IF EXISTS Tyyppi CASCADE;
DROP TABLE IF EXISTS Ainesosat CASCADE;